### ISSUE TITLE
Additional URL pattern to correct

### ISSUE THREAD

**Issue by jcsparks** [CuBoulder/ucb_linkmod#2]
We can probably also assume that anything with a pantheonsite.io domain in a href should be corrected to www.colorado.edu/sitename and preserve the path details after the domain.  

Should talk this through with @kevincrafts and @jbertrand but it's been raised as another pattern that we see that would be good to eliminate.  

An example was found on the D7 site here : https://www.colorado.edu/globalclimatesummit

**Comment by kevincrafts** [comment]
If we could fix this I think it would help catch any full urls that people may use in the site building process.

We had some stuff to catch these a long time ago before we moved to Pantheon.

I think it would also be good to think about what would happen if a site is built at one pantheon subdomain and then moved to another, which has happened quite a few times.

**Comment by jcsparks** [comment]
Mike and I worked on this earlier this week... fix should be going out to production sites on Friday, but you can test it here : https://www.colorado.edu/developer-sandbox/button-link
